#!/usr/bin/env python2

# Script for running gen_utils.gen_save_file() utility function.
# For more information see its documentation.

if __name__ == "__main__":
    import sys
    from gen_utils import gen_save_file

    print(gen_save_file(*sys.argv[1:]))
