#!/usr/bin/env python2

# Script for running gen_utils.gen_progress() utility function.
# For more information see its documentation.

if __name__ == "__main__":
    import sys
    from gen_utils import gen_progress

    print(gen_progress(*sys.argv[1:]))
