#!/usr/bin/env python2

# Script for running gen_utils.gen_info() utility function.
# For more information see its documentation.

if __name__ == "__main__":
    import sys
    from gen_utils import gen_info

    print(gen_info(*sys.argv[1:]))
