#!/usr/bin/env python2

# Script for running gen_utils.gen_warning() utility function.
# For more information see its documentation.

if __name__ == "__main__":
    import sys
    from gen_utils import gen_warning

    print(gen_warning(*sys.argv[1:]))
