# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_autoslug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='data_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
