# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_process_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='named_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
