# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_fix_jsonfields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'default_permissions': (), 'permissions': (('view_storage', 'Can view storage'), ('edit_storage', 'Can edit storage'), ('share_storage', 'Can share storage'), ('owner_storage', 'Is owner of the storage'))},
        ),
    ]
