# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 09:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0011_calculate_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='checksum',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(code='invalid_checksum', message='Checksum is exactly 40 alphanumerics', regex='^[0-9a-f]{40}$')]),
        ),
    ]
