# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0019_data_descriptor_dirty'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='descriptor_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='descriptor_dirty',
            field=models.BooleanField(default=False),
        ),
    ]
