# Generated by Django 4.2.7 on 2023-12-14 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flow", "0018_add_annotationvalue_default_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationvalue",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="values",
                to="flow.annotationfield",
            ),
        ),
    ]
