# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0020_collection_descriptor_dirty'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='descriptor_completed',
            field=models.BooleanField(default=False),
        ),
    ]
