# Generated by Django 4.2.9 on 2024-02-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0022_add_unaccent_extension"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TEXT SEARCH CONFIGURATION simple_unaccent( COPY = simple );"
        ),
        migrations.RunSQL(
            "ALTER TEXT SEARCH CONFIGURATION simple_unaccent "
            + "ALTER MAPPING FOR hword, hword_part, word "
            + "WITH unaccent, simple;"
        ),
    ]
