# Generated by Django 4.2.9 on 2024-02-13 07:33

import os

from django.db import connection, migrations


def load_triggers(apps, schema_editor):
    file_names = [
        "utils.sql",
        "triggers_collection.sql",
        "triggers_entity.sql",
        "triggers_data.sql",
    ]
    with connection.cursor() as c:
        for file_name in file_names:
            file_path = os.path.join(os.path.dirname(__file__), file_name)
            with open(file_path) as fh:
                sql_statement = fh.read()
            c.execute(sql_statement)


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0023_create_unaccent_full_text_search_config"),
    ]

    operations = [
        migrations.RunPython(load_triggers),
        # Update existing entries.
        migrations.RunSQL("UPDATE flow_entity SET id=id;", migrations.RunSQL.noop),
        migrations.RunSQL("UPDATE flow_collection SET id=id;", migrations.RunSQL.noop),
        migrations.RunSQL("UPDATE flow_data SET id=id;", migrations.RunSQL.noop),
    ]
