# Generated by Django 4.2.9 on 2024-02-13 07:00

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0024_update_sql_entity_methods"),
    ]

    operations = [UnaccentExtension()]
