# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 05:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0025_set_get_last_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='entity',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
