# Generated by Django 4.2.16 on 2024-10-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0030_annotationvalue_contributor"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="annotationvalue",
            name="uniquetogether_entity_field",
        ),
        migrations.RemoveField(
            model_name="annotationvalue",
            name="modified",
        ),
        migrations.AddField(
            model_name="annotationvalue",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="annotationvalue",
            name="_value",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddConstraint(
            model_name="annotationvalue",
            constraint=models.UniqueConstraint(
                fields=("entity", "field", "created"),
                name="uniquetogether_entity_field_created",
            ),
        ),
    ]
