# Generated by Django 4.2.16 on 2024-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0031_remove_annotationvalue_uniquetogether_entity_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationvalue",
            name="_value",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
