# Generated by Django 5.1.5 on 2025-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0034_remove_data_idx_data_status_priority_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="process",
            managers=[],
        ),
        migrations.AddField(
            model_name="annotationfield",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="annotationpreset",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="annotationvalue",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collection",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="data",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="descriptorschema",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="entity",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="process",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="relation",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storage",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
