# Generated by Django 3.2.12 on 2022-02-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0004_create_anonymous_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissiongroup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="permissionmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
