# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 02:23
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import versionfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('version', versionfield.VersionField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modules', django.contrib.postgres.fields.jsonb.JSONField()),
                ('description', models.TextField(blank=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('default_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_project', to='flow.Project')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
                'permissions': (('view_app', 'Can view apps'), ('edit_app', 'Can edit apps'), ('share_app', 'Can share apps'), ('add_app', 'Can add apps')),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('version', versionfield.VersionField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modules', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index', models.CharField(max_length=1000)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
                'permissions': (('view_package', 'Can view packages'), ('share_package', 'Can share packages')),
            },
        ),
        migrations.AddField(
            model_name='app',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Package'),
        ),
        migrations.AddField(
            model_name='app',
            name='projects',
            field=models.ManyToManyField(to='flow.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([('slug', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together=set([('slug', 'version')]),
        ),
    ]
