# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
            ],
            options={
                'permissions': (('view_model', 'Can view model'), ('edit_model', 'Can edit model')),
            },
        ),
    ]
