# Generated by Django 3.2.12 on 2022-02-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_squashed_0009_referencedpath_chunk_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="filestorage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="referencedpath",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="storagelocation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
